### ISSUE TITLE
Minecraft not found error

### ISSUE THREAD

**Issue by Dummydud3** [xroix/MCBE-Win10-FOV-Changer#142]
I as a the pro gamer id like to be, i have minecraft on a separate drive, and i prefer not to reinstall minecraft so please do.

**Comment by xroix** [comment]
Please specify your problem more in detail.
Does FOV Changer display an error message or does it crash as an result? And if that's the case, please provide either the error message or the crash_log.txt file.

**Comment by Dummydud3** [comment]
My Minecraft installation is located on a separate drive. The fov changer can’t detect Minecraft on the C: drive. I don’t want to have to reinstall all my texture packs and settings and skins so please have it look on other drive directories. Have the injector search on other drives like F: and E:

**Comment by Dummydud3** [comment]
the error message is: "Minecraft not found!".

**Comment by xroix** [comment]
Sorry for the late response!

The separate drive shouldn't be the issue since FOV-Changer doesn't need the path, only the process name.
Sadly, however, "Minecraft not found" is usually caused by a windows api error.
So please send me the content of the tab "Log" after the error appears.

In the meantime, there are some quick fixes that might possibly resolve your issue:
1. Make sure Minecraft Windows 10 Edition is opened
3. Restart your PC
5. Still not working? Try running FOV-Changer as admin (always!)
6. Still? Try the [beta](http://www.mediafire.com/file/ay5z53t9logj2wz/FOV-Changer-1.1.6-beta.zip/file) and make sure to delete the `storage.json` file
7. Whitelist FOV Changer, if you use a antivirus (Windows Defender excluded, except if it sees it as a threat)

**Comment by xroix** [comment]
Also, in our discord we recently had a case where the solution was to use an older FOV Changer version. Hence:
 6. If you are currently using the beta, use the latest version from the releases. If the latest doesn't work, try 1.1.4 till 1.1.3 (https://github.com/xroix/MCBE-Win10-FOV-Changer/releases)

**Comment by Dummydud3** [comment]
﻿Ok I downloaded 1.1.4 and it works like a charm! My existing mods got in the way of the injector.

**Comment by xroix** [comment]
Glad to hear.

If anyone encounters the same issue, and the steps above do not help, please reopen the issue.

**Comment by HunterOcelot27** [comment]
attempted to load both 1.1.4 and 1.1.3 versions (one after deleting the other). bug reports near identical - they justt didnt load up and the window was just blank. 
[crash_log 1.1.3.txt](https://github.com/xroix/MCBE-Win10-FOV-Changer/files/10289610/crash_log.1.1.3.txt)
[crash_log 1.1.4.txt](https://github.com/xroix/MCBE-Win10-FOV-Changer/files/10289611/crash_log.1.1.4.txt)
happy solstice/merry christmas

**Comment by xroix** [comment]
Thank you for reporting your issue!

I guess – since you are trying to use 1.1.3/4 – you are encountering a "Minecraft not found" error on the newest versions (including the beta). If this is not the case, try those.
(https://www.mediafire.com/file/fzhexy3sn3qrv0a/FOV-Changer-1.1.6-aplha.fix.zip/file https://www.mediafire.com/file/fokxn3papv4rw4x/FOV-Changer-Beta-02.zip/file https://github.com/xroix/MCBE-Win10-FOV-Changer/releases/download/v1.1.5/FOV-Changer.zip)

_Perhaps you already tried it:_
Also try to run FOV Changer as an administrator and make sure that no antivirus interferes. (Seems as if FOV Changer is prevented from creating an icon in the system tray)

But before I start digging through my old codebase, please try the things I mentioned.

**Comment by HunterOcelot27** [comment]
Hi, 

Th 1.1.6 file works with the current version (1.19.5) 

Thank you

**Comment by xroix** [comment]
Great!

As always, if some sort of "Minecraft not found error" occurs, please reopen the issue!
