### ISSUE TITLE
Please add support for 1.18.1201.0 x86

### ISSUE THREAD

**Issue by SuperLlama88888** [xroix/MCBE-Win10-FOV-Changer#152]
Many people use 1.18.12 on the Win10 x86 build since it has easy shader support. Perhaphs an update that detects the x86 client somehow, and then loads a different set of offsets from the server? And anyway there aren't any offsets for 11812010 anyway. Tysm

**Comment by xroix** [comment]
Thank you for your suggestion!

Currently, I am not planning to add support for x86. But if get to work on FOV Changer more extensively again, I will look into it.

Regarding the offsets for 1.18.1201.0 (x86_64): Since I have not migrated the server completely yet (#149), not all working offsets are available. I hope it does not cause any major inconveniences. 

I will close this issue and merge it with #133 to avoid duplicates.

**Comment by SuperLlama88888** [comment]
Thank you!
