### ISSUE TITLE
Detected as virus, malware, etc.

### ISSUE THREAD

**Issue by yichifauzi** [xroix/MCBE-Win10-FOV-Changer#3]
Windows Defender Detect Fov-Changer.zip has trojan Zpevdo.B

**Comment by XroixHD** [comment]
It is a false positive, I already posted more information in the discord. (# known-bugs)
 https://discord.gg/H3hex27

**Comment by RavinMaddHatter** [comment]
I had the same issue in my auto clicker for bedrock.... Let me know if you find a work around.

**Comment by XroixHD** [comment]
@RavinMaddHatter An solution would be using a mix of nuitka and upx (**still gets flagged a bit**). This [repo](https://github.com/Nuitka/NUITKA-Utilities) has got some useful scripts for exactly this. Haven't looked into it completely yet (some errors opening files)

A while ago I modified a script of mentioned repo: https://gist.github.com/XroixHD/47a3db7fe775818db46ed4c889ce8203 But I don't know if this works still.

**Comment by Phantomm1** [comment]
how do u delete after you zip it?

**Comment by Phantomm1** [comment]
it says that it isnt working when i use it

**Comment by xroix** [comment]
This seems to be not related to this issue. Please open a new one.

Still, your problem might occur due to a glitched out FOV-Changer process. Try to restart your PC or find and stop the process via the task manager. If it still persists, please open a new issue and include more information on what exactly isn't working.
